name: test

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@1f8e202ffddf94def7f42f6fa3a482e821489f9c # 2026.07.10.1
      - name: Tap repository
        run: brew tap takesako/niwa "$GITHUB_WORKSPACE"
      - name: Install formula
        run: brew install --build-from-source takesako/niwa/niwa
      - name: Test formula
        run: brew test takesako/niwa/niwa
